
<style type="text/css">

h1, h2, h3, p {
  text-align: center
}

img {
  margin-left: auto;
  margin-right: auto;
}

</style>

```{r setup, echo=FALSE,results='hide', message=FALSE, warning=FALSE}


options(stringsAsFactors = FALSE)

# For the report
library(knitr)
library(xtable)

# For graphics
library(ggplot2)
library(gridExtra)

# For aggregation
library(plyr)
library(reshape2)


# Set default chunk options
opts_chunk$set(echo = FALSE,
               comment = "",
               message = FALSE,
               warning = FALSE,
               error = TRUE,
               fig.width = 10,
               dev="svg",
               tidy=FALSE,
               cache = FALSE)



# Set some plot parameters that will want tweaking
point_size <- 3
line_size <- 1.3
colorwheel <- c("#31A354", "#ADDD8E", "#F03B20", "#43A2CA")


# A function for pretty-printing data.frames
dfprint <- function(df, printdigits = 2) {
    print(
        xtable(format(df, 
                      na.encode = FALSE, 
                      digits = printdigits, 
                      nsmall = printdigits), 
               align = c("l", "l", rep("c", ncol(df) - 1))
        ),
        type = "html",
        include.rownames = FALSE,
        NA.string = "-")
}

# Custom theme
theme_tb <- theme_bw() +
            theme(legend.key.width = unit(.75, "inches"))


```



```{r dataprep}

# Identify the zip file containing the results
datafile <- list.files(pattern = "*.zip")

# Extract the collector list
collectors <- read.csv(unz(datafile, file.path("CSV", "CollectorList.csv")))

# Extract the survey results
results <-  read.csv(unz(datafile, file.path("CSV", "Sheet_1.csv")),
                     check.names = FALSE,
                     na.strings = c("NA", ""))

# Merge collector info onto the results
rescoll <- merge(x = results,
                 y = collectors,
                 by = "CollectorID",
                 all.x = TRUE)


# Get some names we can actually work with - but first, make a crosswalk
namewalk <- data.frame(name = make.names(names(rescoll), unique = TRUE),
                       label = names(rescoll))

names(rescoll) <- make.names(names(rescoll), unique = TRUE)


# Identify which variables are multiple-choice questions
metadata <- c("CollectorID", "RespondentID", "StartDate", "EndDate", "IP.Address",
              "Email.Address", "First.Name", "LastName", "Custom.Data",
              "Title", "Date.Created")

demos <- c("Gender.", "Age.",
           "Race.ethnicity....Asian",
           "Race.ethnicity....Black.African.American",
           "Race.ethnicity....Hispanic.Latino",
           "Race.ethnicity....Native.American",
           "Race.ethnicity....White",
           "Race.ethnicity....Other",
           "Race.ethnicity....Other.1")

comments <- grep(x = names(rescoll), pattern = "Comments.$", value = TRUE)

open_ended <- grep(x = names(rescoll), pattern = "Open.Ended.Response$", value = TRUE)

multiple_choice <- names(rescoll)[!names(rescoll) %in% c(metadata, demos, comments, open_ended)]


# all(names(rescoll) %in% c(metadata, demos, comments, open_ended, multiple_choice))

# Identify which area's results are in question
strat_area <- gsub(x = rescoll$Title[1],
                   pattern = "(\\S*)\\s.*$",
                   replace = "\\1")

# Scrape the dates covered
survdates <- gsub(x = unique(rescoll$Title), 
                  pattern = ".* (\\d{4}-\\d{2}).*$",
                  replace = "\\1")


```


# Customer Satisfaction Survey Results: `r strat_area`
## `r min(survdates)` through `r max(survdates)`

-----------------------------------------------



```{r generate_mc_results}

source("gen_multiple_choice_results.r")

mc_results <- llply(multiple_choice,
                    .fun = function(x) gen_multiple_choice_results(rescoll, x, "Title", namewalk)
)

names(mc_results) <- multiple_choice


```


```{r display_mc_results,results='asis'}


l_ply(mc_results, .fun = function(x) {
  
  cat("## ", x$question_label, "\n")
  
  print(x$answerplot)
  
  cat("\n")
  
  if(class(x$comments) %in% "data.frame") {
      dfprint(x$comments)
  }
  
  cat("\n", "-----------------------------", "\n")

})
  
  
```








